# Put your license key for this software here. Without this key,
# you will not be able to use the full features of this software :(
license-key: ''

# Kerberos Username: this is most likely the 'user' part of your
#  user@bu.edu email.
# (Note: due to security reasons, you cannot save your password
# into this config and must enter it every time manually!)
kerberos-user: 'aseef'

# Whether to enable REAL registrations. When this is set to
# 'True', courses will only be added to the planner. It is
# recommended you do not enable real registrations until you
# are certain that everything is working as intended.
# To enable REAL registrations, set this to 'False'.
# Accepted values are:
# - True
# - False
planner-mode: False

# The semester you are trying to register for.
# Format: [Semester Season] [Year]
# Example: Fall 2024
#
# Valid semester 'semester seasons' are (case insensitive):
# - Fall
# - Spring
# - Summer1
# - Summer2
target-semester: 'Spring 2024'

# The list of courses you want to register for
# Format: [School] [Department] [Course Number] [Section]
# Example: CAS CS 111 A1
course-list:
  - CAS CS 585 A1
  - CAS CS 460 A1
  - CAS CS 460 A2

# If you are trying to register for a course that does not exist,
# should the bot complain (maybe you made a mistake?? If not set this to True.
# Otherwise, leave it to False. One application of this might be that
# if you know for a fact that a course will be added in the future.
ignore-non-existent-courses: False

# You should leave this blank unless the program is unable to
# automatically detect where chrome drivers are.
driver-path: ''

# Whether to enable console colors. Some consoles don't support colors very
# well, and in such case, you may want to disable console colors. Or maybe
# you are just a dull person, and just don't like colors :(.
console-colors: True

# This option enables debug messages. Its primary use is to pin down bugs by
# printing extra log messages with as much information as possible. Only set
# this to True if you are trying to report an issue with the bot. Otherwise,
# logs generated by debug messages could fill up your disk.
debug: False